apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter
  labels:
    type: local
    name: counter
spec:
  storageClassName: nfs-client
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.38.70.127
    path: "/data/nfs1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-client